### ISSUE TITLE
Mise à jour de searchEncode

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#1]
Il y a eu des changements dans la fonction de recherche de l'[API REST D'ENCODE](https://www.encodeproject.org/help/rest-api/) qui empêchaient la fonction [`searchEncode`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L136-L179) de fonctionner correctement. Le problème a été patché avec CharlesJB/ENCODExplorer@0b8f0b654973736301ea616a150aa7748ee6bae3, mais il faudrait analyser le JSON pour s'assurer que toute l'information est conservée. Voir aussi l'[Issue 2](https://github.com/CharlesJB/ENCODExplorer/issues/2) et l'[Issue 10](https://github.com/CharlesJB/ENCODExplorer/issues/10) d'ENCODExplorer.
# TODO:
- [x] Se familiariser avec la fonction [`searchEncode`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L136-L179).
- [x] Analyser le JSON retourné lors d'une recherche avec l'[API REST D'ENCODE](https://www.encodeproject.org/help/rest-api/).
- [x] Valider que toute l'information est présente dans le `data.frame` retourné par [`searchEncode`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L136-L179).
- [x] Adapter la fonction [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134) au besoin:
  - [x] Modifier le code pour que les informations manquantes soient extraites correctement.
  - [x] Ajouter les tests unitaires en conséquence.
  - [x] Modifier le fichier NEWS.

**Comment by louisgendron26** [comment]
Modification a apporté line 73

``` r
else if (column_name == "type")
```

Il n'est pas necessaire d'inclure @type puisque le @ est éliminé en line 123

``` r
table_names <- gsub("@", "", colnames(table))
```

**Comment by louisgendron26** [comment]
Test unitaire a faire :
- data.frames
- list_character
- list_numeric
- list_data.frames
- character
- numeric
