### ISSUE TITLE
Obtenir les URL à partir de l'API REST

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#12]
Il faudrait mettre en place une fonction qui permettrait d'obtenir les URL pour télécharger les fichiers obtenus suite à un appel de `searchEncode`.

Il faut donc trouver une manière d'extraire seulement les URL et seulement pour une liste d'identifiant.
# TODO:
- [x] Étudier le l'[API REST d'ENCODE](https://www.encodeproject.org/help/rest-api/).
- [x] Obtenir les URL en utilisant le plus petit nombre de requête possible (une seule préférablement).
- [x] Préparer une fonction qui ne sera pas importée.
- [x] Appeler cette fonction dans `downloadEncode` lorsqu'il y a des jeux de données qui sont absents d'`encode_df`, mais présent dans le résultat de la recherche.
- [ ] Ajouter les tests unitaires.
- [ ] Mettre le fichier NEWS à jour.
