### ISSUE TITLE
Valider la fonction prepare_ENCODEdb

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#2]
Il y a eu beaucoup de changements important au cours des derniers mois dans la base de données d'ENCODE. Il faut valider que toutes les informations sont correctement extraites de la base de données en utilisant l'API d'ENCODE par la fonction [`prepareENCODEdb`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/prepare_data.R#L68-L133).

Il s'agit d'analyser les tables une à une. À chaque fois qu'un nouveau type de colonne est rencontré, il faut s'assurer que la fonction [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134) ne fait pas d'erreur lors de la conversion en `data.frame`.
# TODO:
- [x] Valider que toute l'information des tables est correctement extraite:
  - [x] [`access_key`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/access_key.json)
  - [x] [`analysis_step`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/analysis_step.json)
  - [x] [`analysis_step_run`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/analysis_step_run.json)
  - [x] [`analysis_step_version`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/analysis_step_version.json)
  - [x] [`annotation`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/annotation.json)
  - [x] [`antibody_approval`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/antibody_approval.json)
  - [x] [`antibody_characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/antibody_characterization.json)
  - [x] [`antibody_lot`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/antibody_lot.json)
  - [x] [`award`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/award.json)
  - [x] [`bigwigcorrelate_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/bigwigcorrelate_quality_metric.json)
  - [x] [`biosample`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/biosample.json)
  - [x] [`biosample_characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/biosample_characterization.json)
  - [x] [`bismark_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/bismark_quality_metric.json)
  - [x] [`characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/characterization.json)
  - [x] [`chipseq_filter_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/chipseq_filter_quality_metric.json)
  - [x] [`construct`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/construct.json)
  - [x] [`construct_characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/construct_characterization.json)
  - [x] [`cpg_correlation_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/cpg_correlation_quality_metric.json)
  - [x] [`dataset`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/dataset.json)
  - [x] [`dnase_peak_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/dnase_peak_quality_metric.json)
  - [x] [`document`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/document.json)
  - [x] [`donor`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/donor.json)
  - [x] [`donor_characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/donor_characterization.json)
  - [x] [`edwbamstats_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/edwbamstats_quality_metric.json)
  - [x] [`edwcomparepeaks_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/edwcomparepeaks_quality_metric.json)
  - [x] [`encode2_chipseq_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/encode2_chipseq_quality_metric.json)
  - [x] [`experiment`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/experiment.json)
  - [x] [`fastqc_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/fastqc_quality_metric.json)
  - [x] [`file`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/file.json)
  - [x] [`file_set`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/file_set.json)
  - [x] [`fly_donor`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/fly_donor.json)
  - [x] [`generic_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/generic_quality_metric.json)
  - [x] [`hotspot_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/hotspot_quality_metric.json)
  - [x] [`human_donor`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/human_donor.json)
  - [x] [`idr_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/idr_quality_metric.json)
  - [x] [`idr_summary_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/idr_summary_quality_metric.json)
  - [x] [`image`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/image.json)
  - [x] [`lab`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/lab.json)
  - [x] [`library`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/library.json)
  - [x] [`mad_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/mad_quality_metric.json)
  - [x] [`matched_set`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/matched_set.json)
  - [x] [`mixins`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/mixins.json)
  - [x] [`mouse_donor`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/mouse_donor.json)
  - [x] [`namespaces`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/namespaces.json)
  - [x] [`organism`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/organism.json)
  - [x] [`organism_development_series`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/organism_development_series.json)
  - [x] [`page`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/page.json)
  - [x] [`pbc_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/pbc_quality_metric.json)
  - [x] [`phantompeaktools_spp_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/phantompeaktools_spp_quality_metric.json)
  - [x] [`pipeline`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/pipeline.json)
  - [x] [`platform`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/platform.json)
  - [x] [`project`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/project.json)
  - [x] [`publication`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/publication.json)
  - [x] [`publication_data`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/publication_data.json)
  - [x] [`quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/quality_metric.json)
  - [x] [`reference`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/reference.json)
  - [x] [`reference_epigenome`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/reference_epigenome.json)
  - [x] [`replicate`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/replicate.json)
  - [x] [`replication_timing_series`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/replication_timing_series.json)
  - [x] [`rnai`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/rnai.json)
  - [x] [`rnai_characterization`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/rnai_characterization.json)
  - [x] [`samtools_flagstats_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/samtools_flagstats_quality_metric.json)
  - [x] [`samtools_stats_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/samtools_stats_quality_metric.json)
  - [x] [`series`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/series.json)
  - [x] [`software`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/software.json)
  - [x] [`software_version`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/software_version.json)
  - [x] [`source`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/source.json)
  - [x] [`star_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/star_quality_metric.json)
  - [x] [`talen`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/talen.json)
  - [x] [`target`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/target.json)
  - [x] [`treatment`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/treatment.json)
  - [x] [`treatment_concentration_series`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/treatment_concentration_series.json)
  - [x] [`treatment_time_series`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/treatment_time_series.json)
  - [x] [`ucsc_browser_composite`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/ucsc_browser_composite.json)
  - [x] [`user`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/user.json)
  - [x] [`worm_donor`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/worm_donor.json)
- [ ] Préparer les tests unitaires de la fonction [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134) pour tester tous les cas rencontrés lors de l'analyse des tables.

**Comment by louisgendron26** [comment]
---------- Empty graph section ---------- 
- access_key
- analysis_step_run
- antibody_approval
- bigwigcorrelate_quality_metric
- construct_characterization
- dnase_peak_quality_metric
- donor_characterization
- edwbamstats_quality_metric
- edwcomparepeaks_quality_metric
- encode2_chipseq_quality_metric
- fastqc_quality_metric
- generic_quality_metric
- hotspot_quality_metric
- pbc_quality_metric
- phantompeaktools_spp_quality_metric
- rnai_characterization

----------- Wrong name section --------
- file_set --> FileSet
- quality_metric --> QualityMetric

------------ Doesn't exist --------------
- mixins
- namespaces

**Comment by louisgendron26** [comment]
The results in the layout section get a weird format for extract_table("page")
