### ISSUE TITLE
Tables absentes

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#3]
Certaines tables ne retournent pas de données lors des requêtes sur l'API REST d'ENCODE.
# TODO:
- [x] Faire la liste des tables qui ne sont pas téléchargées.
- [x] Tester les requêtes directement dans un fureteur (i.e.: Chrome) pour voir si elles fonctionnent.
- [x] Tester avec la première lettre en minuscule et majuscule.
- [x] Modifier le code (au besoin).

**Comment by louisgendron26** [comment]
Voir #2
