### ISSUE TITLE
fuzzySearch

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#7]
Mettre en place une fonction qui aurait une interface similaire à `searchEncode` mais qui rechercherait les résultats dans `encode_df` et non pas sur l'API REST d'ENCODE.

Il faut donc aller séparer la chaîne de caractère fournie par l'utilisateur et retourner tous les fichiers pour lesquels il y a un match d'au moins un colonne des métadonnées avec au moins un des termes de recherche.
# TODO:
- [x] Rechercher des paquets R qui pourraient faciliter cette tâche.
- [x] Implémenter la fonction.
- [ ] Ajouter des tests unitaires.
- [ ] Mettre à jour le fichier NEWS.
