### ISSUE TITLE
Interface graphique

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/Stage_Louis_2016#8]
Implémenter une interface graphique en Shiny pour le paquet ENCODExplorer.
# TODO:
- [ ] Préparer une maquette de l'interface (sur papier).
- [ ] Mettre en place les éléments graphiques de l'interface.
- [ ] Implémenter les fonctionnalités de chaque élément.
- [ ] Mettre à jour le fichier NEWS.
